Add `patched_versions` to informational advisories
Its absence breaks older versions of cargo-audit:

    $ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
    error: error loading advisory database: couldn't parse data: missing field `patched_versions` for key `advisory`
    Exited with code 1